// frontend-next/src/components/charts/TrendChart.tsx
/**
 * 实时 QPS 趋势图（复刻旧 Vue frontend trend-chart.vue）。
 * 使用 echarts-for-react，配置对齐旧版。
 */
import React, { useMemo } from 'react';
import ReactEChartsCore from 'echarts-for-react/lib/core';
import * as echarts from 'echarts/core';
import { LineChart } from 'echarts/charts';
import {
  GridComponent,
  TooltipComponent,
} from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';

echarts.use([LineChart, GridComponent, TooltipComponent, CanvasRenderer]);

interface TrendChartProps {
  times: string[];
  values: number[];
}

const TrendChart: React.FC<TrendChartProps> = ({ times, values }) => {
  const option = useMemo(
    () => ({
      tooltip: {
        trigger: 'axis' as const,
        axisPointer: { type: 'line' as const },
      },
      grid: {
        left: '2%',
        right: '2%',
        top: '10%',
        bottom: '2%',
        containLabel: true,
      },
      xAxis: {
        type: 'category' as const,
        data: times,
        boundaryGap: false,
        axisLine: { show: false },
        axisTick: { show: false },
        splitLine: { show: false },
      },
      yAxis: {
        type: 'value' as const,
        axisLine: { show: false },
        axisTick: { show: false },
        splitLine: {
          show: true,
          lineStyle: { type: 'dashed' as const, color: '#eeeeee' },
        },
      },
      series: [
        {
          name: 'QPS',
          type: 'line' as const,
          smooth: true,
          showSymbol: false,
          itemStyle: { color: '#06b6d4' },
          areaStyle: {
            color: {
              type: 'linear' as const,
              x: 0,
              y: 0,
              x2: 0,
              y2: 1,
              colorStops: [
                { offset: 0, color: 'rgba(6, 182, 212, 0.4)' },
                { offset: 1, color: 'rgba(6, 182, 212, 0.05)' },
              ],
            },
          },
          data: values,
        },
      ],
    }),
    [times, values],
  );

  return (
    <ReactEChartsCore
      echarts={echarts}
      option={option}
      style={{ height: 300, width: '100%' }}
      notMerge
      lazyUpdate
    />
  );
};

export default TrendChart;

// frontend/src/views/dashboard/modules/trend-chart.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useEcharts } from '@/hooks/common/echarts';
import { getTrendData } from '../data';

const { domRef, updateOptions } = useEcharts(() => ({
  tooltip: {
    trigger: 'axis',
    axisPointer: { type: 'line' }
  },
  grid: {
    left: '2%',
    right: '2%',
    top: '10%',
    bottom: '2%',
    containLabel: true
  },
  xAxis: {
    type: 'category',
    data: [],
    boundaryGap: false,
    axisLine: { show: false },
    axisTick: { show: false },
    splitLine: { show: false }
  },
  yAxis: {
    type: 'value',
    axisLine: { show: false },
    axisTick: { show: false },
    splitLine: { 
      show: true, 
      lineStyle: { type: 'dashed', color: '#eeeeee' } 
    }
  },
  series: []
}));

const data = getTrendData();

updateOptions(opts => {
  opts.xAxis = { ...opts.xAxis, data: data.times };
  opts.series = [
    {
      name: 'QPS',
      type: 'line',
      smooth: true,
      showSymbol: false,
      itemStyle: { color: '#06b6d4' },
      areaStyle: {
        color: {
          type: 'linear',
          x: 0, y: 0, x2: 0, y2: 1,
          colorStops: [
            { offset: 0, color: 'rgba(6, 182, 212, 0.4)' },
            { offset: 1, color: 'rgba(6, 182, 212, 0.05)' }
          ]
        }
      },
      data: data.qps
    }
  ];
  return opts;
});
</script>

<template>
  <NCard title="实时 QPS 趋势" class="h-full rounded-2xl border-none shadow-sm">
    <template #header-extra>
      <div class="flex items-center gap-2">
        <NTag size="small" type="primary" round>Live</NTag>
      </div>
    </template>
    <div ref="domRef" class="h-300px"></div>
  </NCard>
</template>
