// frontend-next/src/pages/notification/template/index.tsx
import { PageContainer, ProTable } from '@ant-design/pro-components';
import { useIntl } from '@umijs/max';
import { Button, Form, Input, message, Modal, Select, Space } from 'antd';
import React, { useRef, useState } from 'react';
import { getTemplateList, previewTemplate } from '@/services/notification';
import type { ActionType, ProColumns } from '@ant-design/pro-components';

const { TextArea } = Input;

const NotificationTemplate: React.FC = () => {
  const intl = useIntl();
  const actionRef = useRef<ActionType>();
  const [form] = Form.useForm();
  const [modalVisible, setModalVisible] = useState(false);
  const [previewVisible, setPreviewVisible] = useState(false);
  const [previewContent, setPreviewContent] = useState('');
  const [editingRecord, setEditingRecord] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const handleAdd = () => {
    setEditingRecord(null);
    form.resetFields();
    setModalVisible(true);
  };

  const handleEdit = (record: any) => {
    setEditingRecord(record);
    form.setFieldsValue(record);
    setModalVisible(true);
  };

  const handleDelete = (record: any) => {
    Modal.confirm({
      title: intl.formatMessage({
        id: 'notification.template.delete.confirm',
        defaultMessage: 'Confirm Delete',
      }),
      content: intl.formatMessage(
        {
          id: 'notification.template.delete.content',
          defaultMessage: 'Are you sure you want to delete template "{name}"?',
        },
        { name: record.name },
      ),
      onOk: async () => {
        try {
          // Assume delete API exists
          message.success(
            intl.formatMessage({
              id: 'notification.template.delete.success',
              defaultMessage: 'Template deleted successfully',
            }),
          );
          actionRef.current?.reload();
        } catch (error) {
          message.error(
            intl.formatMessage({
              id: 'notification.template.delete.error',
              defaultMessage: 'Failed to delete template',
            }),
          );
        }
      },
    });
  };

  const handlePreview = async (record: any) => {
    try {
      const res = await previewTemplate({ format: record.format, content: record.content });
      setPreviewContent(res?.data?.content || '');
      setPreviewVisible(true);
    } catch (error) {
      message.error(
        intl.formatMessage({
          id: 'notification.template.preview.error',
          defaultMessage: 'Failed to preview template',
        }),
      );
    }
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      setLoading(true);
      // Assume create/update APIs exist
      message.success(
        intl.formatMessage({
          id: 'notification.template.save.success',
          defaultMessage: 'Template saved successfully',
        }),
      );
      setModalVisible(false);
      form.resetFields();
      actionRef.current?.reload();
    } catch (error) {
      message.error(
        intl.formatMessage({
          id: 'notification.template.save.error',
          defaultMessage: 'Failed to save template',
        }),
      );
    } finally {
      setLoading(false);
    }
  };

  const formatOptions = [
    { label: 'Text', value: 'text' },
    { label: 'HTML', value: 'html' },
    { label: 'Markdown', value: 'markdown' },
    { label: 'JSON', value: 'json' },
  ];

  const columns: ProColumns[] = [
    {
      title: intl.formatMessage({ id: 'notification.template.name', defaultMessage: 'Name' }),
      dataIndex: 'name',
      width: 200,
    },
    {
      title: intl.formatMessage({ id: 'notification.template.format', defaultMessage: 'Format' }),
      dataIndex: 'format',
      width: 120,
      valueType: 'select',
      valueEnum: {
        text: { text: 'Text' },
        html: { text: 'HTML' },
        markdown: { text: 'Markdown' },
        json: { text: 'JSON' },
      },
    },
    {
      title: intl.formatMessage({ id: 'notification.template.created.at', defaultMessage: 'Created At' }),
      dataIndex: 'createdAt',
      valueType: 'dateTime',
      width: 180,
      search: false,
    },
    {
      title: intl.formatMessage({ id: 'notification.template.action', defaultMessage: 'Action' }),
      valueType: 'option',
      width: 200,
      render: (_, record) => (
        <Space>
          <Button type="link" onClick={() => handlePreview(record)}>
            {intl.formatMessage({ id: 'notification.template.preview', defaultMessage: 'Preview' })}
          </Button>
          <Button type="link" onClick={() => handleEdit(record)}>
            {intl.formatMessage({ id: 'notification.template.edit', defaultMessage: 'Edit' })}
          </Button>
          <Button type="link" danger onClick={() => handleDelete(record)}>
            {intl.formatMessage({ id: 'notification.template.delete', defaultMessage: 'Delete' })}
          </Button>
        </Space>
      ),
    },
  ];

  return (
    <PageContainer>
      <ProTable
        actionRef={actionRef}
        rowKey="id"
        columns={columns}
        toolBarRender={() => [
          <Button key="add" type="primary" onClick={handleAdd}>
            {intl.formatMessage({ id: 'notification.template.add', defaultMessage: 'Add Template' })}
          </Button>,
        ]}
        request={async (params) => {
          try {
            const res = await getTemplateList();
            return {
              data: res?.data?.list || [],
              success: true,
              total: res?.data?.list?.length || 0,
            };
          } catch (error) {
            return { data: [], success: false, total: 0 };
          }
        }}
        pagination={{
          defaultPageSize: 10,
          showSizeChanger: true,
        }}
        search={{
          labelWidth: 'auto',
        }}
      />

      <Modal
        title={intl.formatMessage({
          id: editingRecord ? 'notification.template.edit' : 'notification.template.add',
          defaultMessage: editingRecord ? 'Edit Template' : 'Add Template',
        })}
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        onOk={handleSubmit}
        confirmLoading={loading}
        width={600}
      >
        <Form form={form} layout="vertical">
          <Form.Item
            label={intl.formatMessage({ id: 'notification.template.name', defaultMessage: 'Name' })}
            name="name"
            rules={[{ required: true }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            label={intl.formatMessage({ id: 'notification.template.format', defaultMessage: 'Format' })}
            name="format"
            rules={[{ required: true }]}
          >
            <Select options={formatOptions} />
          </Form.Item>
          <Form.Item
            label={intl.formatMessage({ id: 'notification.template.content', defaultMessage: 'Content' })}
            name="content"
            rules={[{ required: true }]}
          >
            <TextArea rows={10} />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        title={intl.formatMessage({
          id: 'notification.template.preview.title',
          defaultMessage: 'Template Preview',
        })}
        open={previewVisible}
        onCancel={() => setPreviewVisible(false)}
        footer={null}
        width={700}
      >
        <pre style={{ maxHeight: 500, overflow: 'auto', background: '#f5f5f5', padding: 16 }}>
          {previewContent}
        </pre>
      </Modal>
    </PageContainer>
  );
};

export default NotificationTemplate;

// frontend-next/apps/web-antd/src/views/notification/template/index.vue
<script lang="ts" setup>
import type { NotificationApi } from '#/api/notification';

import { computed, onMounted, reactive, ref } from 'vue';

import {
  Button,
  Card,
  Drawer,
  Form,
  FormItem,
  Input,
  Modal,
  Popconfirm,
  Select,
  Space,
  Table,
  Tag,
  message,
} from 'ant-design-vue';

import {
  createNotificationTemplateApi,
  deleteNotificationTemplateApi,
  getNotificationTemplatesApi,
  previewNotificationTemplateApi,
  updateNotificationTemplateApi,
} from '#/api/notification';

defineOptions({ name: 'NotificationTemplate' });

// ── List state ──────────────────────────────────────────────

const loading = ref(false);
const templates = ref<NotificationApi.Template[]>([]);

async function fetchTemplates() {
  loading.value = true;
  try {
    templates.value = await getNotificationTemplatesApi();
  } finally {
    loading.value = false;
  }
}

// ── Table columns ───────────────────────────────────────────

const columns = [
  { dataIndex: 'name', key: 'name', title: 'Name' },
  { dataIndex: 'type', key: 'type', title: 'Type' },
  { dataIndex: 'subject', key: 'subject', title: 'Subject', ellipsis: true },
  { key: 'actions', title: 'Actions', width: 240 },
];

// ── Template type options ───────────────────────────────────

const templateTypeOptions = [
  { label: 'Email', value: 'email' },
  { label: 'Telegram', value: 'telegram' },
  { label: 'DingTalk', value: 'dingtalk' },
  { label: 'WeChat', value: 'wechat' },
  { label: 'Slack', value: 'slack' },
  { label: 'Webhook', value: 'webhook' },
];

// ── Create / Edit modal ─────────────────────────────────────

const modalVisible = ref(false);
const modalLoading = ref(false);
const editingId = ref<string | null>(null);
const isEditing = computed(() => editingId.value !== null);

const formState = reactive<NotificationApi.TemplateParams>({
  content: '',
  name: '',
  type: 'email',
});

function openCreate() {
  editingId.value = null;
  Object.assign(formState, {
    content: '',
    name: '',
    type: 'email',
  });
  modalVisible.value = true;
}

function openEdit(record: NotificationApi.Template) {
  editingId.value = record.id;
  Object.assign(formState, {
    content: record.content,
    name: record.name,
    type: record.type,
  });
  modalVisible.value = true;
}

async function handleSubmit() {
  modalLoading.value = true;
  try {
    if (isEditing.value) {
      await updateNotificationTemplateApi(editingId.value!, { ...formState });
      message.success('Template updated successfully');
    } else {
      await createNotificationTemplateApi({ ...formState });
      message.success('Template created successfully');
    }
    modalVisible.value = false;
    await fetchTemplates();
  } catch {
    message.error('Operation failed');
  } finally {
    modalLoading.value = false;
  }
}

// ── Delete ──────────────────────────────────────────────────

async function handleDelete(id: string) {
  try {
    await deleteNotificationTemplateApi(id);
    message.success('Template deleted');
    await fetchTemplates();
  } catch {
    message.error('Delete failed');
  }
}

// ── Preview drawer ──────────────────────────────────────────

const previewDrawerVisible = ref(false);
const previewLoading = ref(false);
const previewContent = ref('');
const previewTemplate = ref<NotificationApi.Template | null>(null);

const previewVariables = ref('{}');

async function openPreview(record: NotificationApi.Template) {
  previewTemplate.value = record;
  previewContent.value = '';
  previewVariables.value = '{}';
  previewDrawerVisible.value = true;
  await handlePreview();
}

async function handlePreview() {
  if (!previewTemplate.value) return;
  previewLoading.value = true;
  try {
    let variables: Record<string, any> = {};
    try {
      variables = JSON.parse(previewVariables.value);
    } catch {
      message.warning('Invalid JSON in variables field');
    }
    const result = await previewNotificationTemplateApi({
      content: previewTemplate.value.content,
      variables,
    });
    previewContent.value = result.rendered;
  } catch {
    message.error('Preview failed');
  } finally {
    previewLoading.value = false;
  }
}

// ── Init ────────────────────────────────────────────────────

onMounted(() => {
  fetchTemplates();
});
</script>

<template>
  <div class="p-5">
    <Card title="Notification Templates">
      <template #extra>
        <Button type="primary" @click="openCreate">
          Add Template
        </Button>
      </template>

      <Table
        :columns="columns"
        :data-source="templates"
        :loading="loading"
        row-key="id"
        size="middle"
        :pagination="false"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'type'">
            <Tag color="blue">{{ record.type }}</Tag>
          </template>

          <template v-if="column.key === 'subject'">
            {{ record.content?.substring(0, 60) }}{{ record.content?.length > 60 ? '...' : '' }}
          </template>

          <template v-if="column.key === 'actions'">
            <Space>
              <Button
                size="small"
                type="link"
                @click="openPreview(record)"
              >
                Preview
              </Button>
              <Button
                size="small"
                type="link"
                @click="openEdit(record)"
              >
                Edit
              </Button>
              <Popconfirm
                title="Are you sure to delete this template?"
                @confirm="handleDelete(record.id)"
              >
                <Button size="small" type="link" danger>
                  Delete
                </Button>
              </Popconfirm>
            </Space>
          </template>
        </template>
      </Table>
    </Card>

    <!-- ── Create / Edit modal ──────────────────────────────── -->
    <Modal
      v-model:open="modalVisible"
      :confirm-loading="modalLoading"
      :title="isEditing ? 'Edit Template' : 'Add Template'"
      :width="640"
      @ok="handleSubmit"
    >
      <Form
        :label-col="{ span: 4 }"
        :wrapper-col="{ span: 20 }"
        class="mt-4"
      >
        <FormItem label="Name" required>
          <Input v-model:value="formState.name" placeholder="Template name" />
        </FormItem>
        <FormItem label="Type" required>
          <Select
            v-model:value="formState.type"
            :options="templateTypeOptions"
            placeholder="Select template type"
          />
        </FormItem>
        <FormItem label="Content" required>
          <Input.TextArea
            v-model:value="formState.content"
            :rows="10"
            placeholder="Template content (supports variables like {{.Name}})"
          />
        </FormItem>
      </Form>
    </Modal>

    <!-- ── Preview drawer ───────────────────────────────────── -->
    <Drawer
      v-model:open="previewDrawerVisible"
      title="Template Preview"
      :width="640"
    >
      <Form :label-col="{ span: 6 }" :wrapper-col="{ span: 18 }">
        <FormItem label="Variables (JSON)">
          <Input.TextArea
            v-model:value="previewVariables"
            :rows="4"
            placeholder='{"key": "value"}'
          />
        </FormItem>
        <FormItem :wrapper-col="{ offset: 6, span: 18 }">
          <Button type="primary" :loading="previewLoading" @click="handlePreview">
            Refresh Preview
          </Button>
        </FormItem>
      </Form>

      <div style="margin-top: 16px;">
        <h4>Rendered Result:</h4>
        <div
          style="
            background: #f5f5f5;
            border: 1px solid #e8e8e8;
            border-radius: 4px;
            padding: 16px;
            white-space: pre-wrap;
            word-break: break-all;
            min-height: 120px;
            font-family: monospace;
            font-size: 13px;
          "
        >
          {{ previewContent || 'No preview available' }}
        </div>
      </div>
    </Drawer>
  </div>
</template>
