// frontend-next/apps/src/views/manage/user/index.vue
<script setup lang="ts">
import { h, onMounted, reactive, ref } from 'vue';
import {
  Button,
  Card,
  Form,
  Input,
  message,
  Modal,
  Popconfirm,
  Select,
  Space,
  Table,
  Tag,
} from 'ant-design-vue';
import {
  createUserApi,
  deleteUserApi,
  getUserListApi,
  toggleUserStatusApi,
  updateUserApi,
} from '#/api/system/user';
import { getRoleListApi } from '#/api/system/role';

defineOptions({ name: 'ManageUser' });

interface UserItem {
  id: number;
  username: string;
  roles: string[];
  status: number;
  createdAt: string;
}

const loading = ref(false);
const dataSource = ref<UserItem[]>([]);
const total = ref(0);
const searchUsername = ref('');

const pagination = reactive({
  current: 1,
  pageSize: 20,
  showSizeChanger: true,
  pageSizeOptions: ['10', '20', '50', '100'],
  showTotal: (t: number) => `共 ${t} 条`,
});

const showModal = ref(false);
const modalType = ref<'add' | 'edit'>('add');
const submitLoading = ref(false);
const formState = reactive({
  id: 0,
  username: '',
  password: '',
  roles: [] as string[],
});

const roleOptions = ref<Array<{ label: string; value: string }>>([]);

const roleMap: Record<string, string> = {
  admin: '管理员',
  analyst: '分析师',
  viewer: '访客',
};

const columns = [
  { dataIndex: 'id', key: 'id', title: 'ID', width: 80 },
  { dataIndex: 'username', key: 'username', title: '用户名', width: 150 },
  { key: 'roles', title: '角色', width: 200 },
  { key: 'status', title: '状态', width: 100 },
  { dataIndex: 'createdAt', key: 'createdAt', title: '创建时间', width: 180 },
  { key: 'actions', title: '操作', width: 200 },
];

async function fetchRoleOptions() {
  try {
    const list = await getRoleListApi();
    if (Array.isArray(list)) {
      roleOptions.value = list.map((role: any) => ({
        label: role.displayName || role.name,
        value: role.name,
      }));
    }
  } catch {
    // error handled by interceptor
  }
}

async function fetchData() {
  loading.value = true;
  try {
    const params: Record<string, any> = {
      page: pagination.current,
      pageSize: pagination.pageSize,
    };
    if (searchUsername.value) {
      params.username = searchUsername.value;
    }
    const data = await getUserListApi(params);
    dataSource.value = data?.list ?? [];
    total.value = data?.total ?? 0;
  } catch {
    message.error('加载失败');
  } finally {
    loading.value = false;
  }
}

function handleSearch() {
  pagination.current = 1;
  fetchData();
}

function handleTableChange(pag: any) {
  pagination.current = pag.current;
  pagination.pageSize = pag.pageSize;
  fetchData();
}

function handleAdd() {
  modalType.value = 'add';
  formState.username = '';
  formState.password = '';
  formState.roles = ['viewer'];
  showModal.value = true;
}

function handleEdit(record: UserItem) {
  modalType.value = 'edit';
  formState.id = record.id;
  formState.username = record.username;
  formState.password = '';
  formState.roles = [...record.roles];
  showModal.value = true;
}

async function handleDelete(id: number) {
  try {
    await deleteUserApi(id);
    message.success('删除成功');
    fetchData();
  } catch {
    message.error('删除失败');
  }
}

async function handleToggleStatus(record: UserItem) {
  try {
    await toggleUserStatusApi(record.id);
    message.success(record.status === 1 ? '用户已冻结' : '用户已解冻');
    fetchData();
  } catch {
    message.error('操作失败');
  }
}

async function handleSubmit() {
  if (!formState.username) {
    message.warning('请输入用户名');
    return;
  }
  if (modalType.value === 'add' && !formState.password) {
    message.warning('请输入密码');
    return;
  }

  submitLoading.value = true;
  try {
    if (modalType.value === 'add') {
      await createUserApi({
        username: formState.username,
        password: formState.password,
        roles: formState.roles,
      });
      message.success('新增成功');
    } else {
      const payload: Record<string, any> = { roles: formState.roles };
      if (formState.password) {
        payload.password = formState.password;
      }
      await updateUserApi(formState.id, payload);
      message.success('编辑成功');
    }
    showModal.value = false;
    fetchData();
  } catch {
    message.error('操作失败');
  } finally {
    submitLoading.value = false;
  }
}

onMounted(() => {
  fetchRoleOptions();
  fetchData();
});
</script>

<template>
  <div class="h-full overflow-hidden">
    <Card title="用户管理" :bordered="false" class="h-full rounded-lg shadow-sm">
      <template #extra>
        <Space>
          <Input
            v-model:value="searchUsername"
            placeholder="搜索用户名"
            allow-clear
            @press-enter="handleSearch"
          />
          <Button type="primary" @click="handleSearch">搜索</Button>
          <Button type="primary" ghost @click="handleAdd">新增用户</Button>
        </Space>
      </template>

      <Table
        :columns="columns"
        :data-source="dataSource"
        :loading="loading"
        :pagination="{ ...pagination, total }"
        row-key="id"
        size="middle"
        @change="handleTableChange"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'roles'">
            <Space>
              <Tag
                v-for="role in record.roles"
                :key="role"
                :color="role === 'admin' ? 'green' : 'blue'"
              >
                {{ roleMap[role] || role }}
              </Tag>
            </Space>
          </template>
          <template v-if="column.key === 'status'">
            <Tag :color="record.status === 1 ? 'green' : 'red'">
              {{ record.status === 1 ? '启用' : '禁用' }}
            </Tag>
          </template>
          <template v-if="column.key === 'actions'">
            <Space>
              <Button type="link" size="small" @click="handleEdit(record)">
                编辑
              </Button>
              <Button
                type="link"
                size="small"
                :style="{ color: record.status === 1 ? '#faad14' : '#52c41a' }"
                @click="handleToggleStatus(record)"
              >
                {{ record.status === 1 ? '冻结' : '解冻' }}
              </Button>
              <Popconfirm
                title="确认永久删除该用户吗？此操作无法恢复！"
                ok-text="确认"
                cancel-text="取消"
                @confirm="handleDelete(record.id)"
              >
                <Button type="link" size="small" danger>删除</Button>
              </Popconfirm>
            </Space>
          </template>
        </template>
      </Table>
    </Card>

    <Modal
      :open="showModal"
      :title="modalType === 'add' ? '新增用户' : '编辑用户'"
      :confirm-loading="submitLoading"
      @cancel="showModal = false"
      @ok="handleSubmit"
    >
      <Form layout="vertical" style="margin-top: 16px;">
        <Form.Item label="用户名" required>
          <Input
            v-model:value="formState.username"
            :disabled="modalType === 'edit'"
            placeholder="请输入用户名"
          />
        </Form.Item>
        <Form.Item
          :label="modalType === 'edit' ? '新密码（留空则不修改）' : '密码'"
          :required="modalType === 'add'"
        >
          <Input.Password
            v-model:value="formState.password"
            placeholder="请输入密码"
          />
        </Form.Item>
        <Form.Item label="角色">
          <Select
            v-model:value="formState.roles"
            mode="multiple"
            :options="roleOptions"
            placeholder="请选择角色"
          />
        </Form.Item>
      </Form>
    </Modal>
  </div>
</template>

// frontend-next/src/pages/manage/user/index.tsx
/**
 * User Management Page (Task 14.1)
 *
 * Paginated user table with search, add/edit/delete users via modal forms,
 * toggle enable/disable, and role assignment from API-fetched roles.
 */
import { useEffect, useState, useCallback } from 'react';
import {
  Table,
  Button,
  Modal,
  Space,
  message,
  Card,
  Tag,
  Form,
  Input,
  Select,
  Switch,
  Popconfirm,
} from 'antd';
import { PageContainer } from '@ant-design/pro-components';
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  SearchOutlined,
} from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import { request } from '@/utils/request';

// ---------------------------------------------------------------------------
// Inline service functions for user management
// ---------------------------------------------------------------------------

interface UserItem {
  id: number;
  username: string;
  displayName: string;
  email: string;
  phone: string;
  roles: string[];
  status: '1' | '2';
  createdAt: string;
  updatedAt: string;
}

async function fetchUserList(params: { page: number; pageSize: number; username?: string }) {
  return request<{ list: UserItem[]; total: number }>({
    url: '/api/user/list',
    params: { current: params.page, size: params.pageSize, username: params.username },
  });
}

async function fetchCreateUser(data: {
  username: string;
  displayName: string;
  email: string;
  phone: string;
  roles: string[];
  password?: string;
}) {
  return request<void>({ url: '/api/user', method: 'post', data });
}

async function fetchUpdateUser(id: number, data: Partial<UserItem & { password?: string }>) {
  return request<void>({ url: `/api/user/${id}`, method: 'put', data });
}

async function fetchDeleteUser(id: number) {
  return request<void>({ url: `/api/user/${id}`, method: 'delete' });
}

async function fetchToggleUserStatus(id: number, status: '1' | '2') {
  return request<void>({ url: `/api/user/${id}/status`, method: 'put', data: { status } });
}

async function fetchRoleOptions() {
  return request<{ list: { name: string; displayName: string }[] }>({ url: '/api/role/list' });
}

// ---------------------------------------------------------------------------
// Page component
// ---------------------------------------------------------------------------

export default function UserManagementPage() {
  const [loading, setLoading] = useState(false);
  const [users, setUsers] = useState<UserItem[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [searchUsername, setSearchUsername] = useState('');
  const [roles, setRoles] = useState<{ name: string; displayName: string }[]>([]);

  // Modal state
  const [modalVisible, setModalVisible] = useState(false);
  const [editingUser, setEditingUser] = useState<UserItem | null>(null);
  const [form] = Form.useForm();
  const [saving, setSaving] = useState(false);

  const loadUsers = useCallback(async (p: number, ps: number, username?: string) => {
    setLoading(true);
    const { data, error } = await fetchUserList({ page: p, pageSize: ps, username });
    if (error) {
      message.error(error.message || 'Failed to load users');
    } else if (data) {
      setUsers(data.list || []);
      setTotal(data.total || 0);
    }
    setLoading(false);
  }, []);

  const loadRoles = useCallback(async () => {
    const { data } = await fetchRoleOptions();
    if (data) {
      setRoles(data.list || []);
    }
  }, []);

  useEffect(() => {
    loadUsers(page, pageSize, searchUsername);
    loadRoles();
  }, [page, pageSize, loadUsers, loadRoles]);

  const handleSearch = () => {
    setPage(1);
    loadUsers(1, pageSize, searchUsername);
  };

  const handleReset = () => {
    setSearchUsername('');
    setPage(1);
    loadUsers(1, pageSize, '');
  };

  const handleAdd = () => {
    setEditingUser(null);
    form.resetFields();
    setModalVisible(true);
  };

  const handleEdit = (user: UserItem) => {
    setEditingUser(user);
    form.setFieldsValue({
      username: user.username,
      displayName: user.displayName,
      email: user.email,
      phone: user.phone,
      roles: user.roles,
    });
    setModalVisible(true);
  };

  const handleDelete = async (id: number) => {
    const { error } = await fetchDeleteUser(id);
    if (error) {
      message.error(error.message || 'Failed to delete user');
    } else {
      message.success('User deleted successfully');
      loadUsers(page, pageSize, searchUsername);
    }
  };

  const handleToggleStatus = async (user: UserItem) => {
    const newStatus: '1' | '2' = user.status === '1' ? '2' : '1';
    const { error } = await fetchToggleUserStatus(user.id, newStatus);
    if (error) {
      message.error(error.message || 'Failed to toggle status');
    } else {
      message.success(`User ${newStatus === '1' ? 'enabled' : 'disabled'} successfully`);
      loadUsers(page, pageSize, searchUsername);
    }
  };

  const handleSaveUser = async () => {
    try {
      const values = await form.validateFields();
      setSaving(true);

      if (editingUser) {
        const { error } = await fetchUpdateUser(editingUser.id, values);
        if (error) {
          message.error(error.message || 'Failed to update user');
        } else {
          message.success('User updated successfully');
          setModalVisible(false);
          loadUsers(page, pageSize, searchUsername);
        }
      } else {
        const { error } = await fetchCreateUser(values);
        if (error) {
          message.error(error.message || 'Failed to create user');
        } else {
          message.success('User created successfully');
          setModalVisible(false);
          setPage(1);
          loadUsers(1, pageSize, searchUsername);
        }
      }
    } catch {
      // Form validation failed
    }
    setSaving(false);
  };

  const handleCancelModal = () => {
    setModalVisible(false);
    setEditingUser(null);
    form.resetFields();
  };

  const columns: ColumnsType<UserItem> = [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      width: 80,
    },
    {
      title: 'Username',
      dataIndex: 'username',
      key: 'username',
      width: 140,
    },
    {
      title: 'Display Name',
      dataIndex: 'displayName',
      key: 'displayName',
      width: 150,
    },
    {
      title: 'Email',
      dataIndex: 'email',
      key: 'email',
      width: 200,
    },
    {
      title: 'Phone',
      dataIndex: 'phone',
      key: 'phone',
      width: 140,
    },
    {
      title: 'Roles',
      dataIndex: 'roles',
      key: 'roles',
      width: 200,
      render: (userRoles: string[]) => (
        <Space size={[0, 4]} wrap>
          {userRoles?.map(r => (
            <Tag key={r} color="blue">
              {r}
            </Tag>
          ))}
        </Space>
      ),
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: '1' | '2', record: UserItem) => (
        <Switch
          checked={status === '1'}
          checkedChildren="Enabled"
          unCheckedChildren="Disabled"
          onChange={() => handleToggleStatus(record)}
        />
      ),
    },
    {
      title: 'Created At',
      dataIndex: 'createdAt',
      key: 'createdAt',
      width: 180,
      render: (text: string) => (text ? new Date(text).toLocaleString() : '-'),
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 160,
      fixed: 'right',
      render: (_: unknown, record: UserItem) => (
        <Space>
          <Button type="link" icon={<EditOutlined />} onClick={() => handleEdit(record)}>
            Edit
          </Button>
          <Popconfirm
            title="Are you sure you want to delete this user?"
            onConfirm={() => handleDelete(record.id)}
            okText="Yes"
            cancelText="No"
          >
            <Button type="link" danger icon={<DeleteOutlined />}>
              Delete
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <PageContainer title="User Management">
      <Card>
        {/* Search bar */}
        <Space style={{ marginBottom: 16 }}>
          <Input
            placeholder="Search by username"
            value={searchUsername}
            onChange={(e) => setSearchUsername(e.target.value)}
            onPressEnter={handleSearch}
            style={{ width: 240 }}
            allowClear
          />
          <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
            Search
          </Button>
          <Button onClick={handleReset}>Reset</Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            Add User
          </Button>
        </Space>

        {/* User table */}
        <Table<UserItem>
          columns={columns}
          dataSource={users}
          rowKey="id"
          loading={loading}
          scroll={{ x: 1200 }}
          pagination={{
            current: page,
            pageSize,
            total,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (t) => `Total ${t} users`,
            onChange: (p, ps) => {
              setPage(p);
              setPageSize(ps);
            },
          }}
        />
      </Card>

      {/* Add/Edit User Modal */}
      <Modal
        title={editingUser ? 'Edit User' : 'Add User'}
        open={modalVisible}
        onOk={handleSaveUser}
        onCancel={handleCancelModal}
        confirmLoading={saving}
        destroyOnClose
      >
        <Form
          form={form}
          layout="vertical"
          autoComplete="off"
        >
          <Form.Item
            label="Username"
            name="username"
            rules={[{ required: true, message: 'Please enter username' }]}
          >
            <Input disabled={!!editingUser} placeholder="Enter username" />
          </Form.Item>
          <Form.Item
            label="Display Name"
            name="displayName"
            rules={[{ required: true, message: 'Please enter display name' }]}
          >
            <Input placeholder="Enter display name" />
          </Form.Item>
          <Form.Item
            label="Email"
            name="email"
            rules={[
              { required: true, message: 'Please enter email' },
              { type: 'email', message: 'Invalid email format' },
            ]}
          >
            <Input placeholder="Enter email" />
          </Form.Item>
          <Form.Item
            label="Phone"
            name="phone"
          >
            <Input placeholder="Enter phone number" />
          </Form.Item>
          <Form.Item
            label="Roles"
            name="roles"
            rules={[{ required: true, message: 'Please select at least one role' }]}
          >
            <Select
              mode="multiple"
              placeholder="Select roles"
              options={roles.map(r => ({ label: r.displayName, value: r.name }))}
            />
          </Form.Item>
          {!editingUser && (
            <Form.Item
              label="Password"
              name="password"
              rules={[
                { required: true, message: 'Please enter password' },
                { min: 6, message: 'Password must be at least 6 characters' },
              ]}
            >
              <Input.Password placeholder="Enter password" />
            </Form.Item>
          )}
        </Form>
      </Modal>
    </PageContainer>
  );
}
