// frontend-next/apps/src/views/caddy/system-log/index.vue
<script lang="ts" setup>
import { h, onMounted, reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';

import {
  Button,
  Card,
  Form,
  FormItem,
  InputSearch,
  Select,
  SelectOption,
  Space,
  Table,
  Tag,
} from 'ant-design-vue';

import { getSystemLogsApi } from '#/api/system/log';
import type { SystemLogApi } from '#/api/system/log';

// --------------- state ---------------
const loading = ref(false);
const dataSource = ref<SystemLogApi.LogItem[]>([]);
const total = ref(0);

const pagination = reactive({
  current: 1,
  pageSize: 20,
  showSizeChanger: true,
  pageSizeOptions: ['10', '20', '50', '100'],
  showTotal: (t: number) => `Total ${t} records`,
});

const filters = reactive({
  keyword: '',
  level: undefined as string | undefined,
});

// --------------- columns ---------------
const columns = [
  {
    title: 'Timestamp',
    dataIndex: 'timestamp',
    key: 'timestamp',
    width: 180,
    sorter: true,
  },
  {
    title: 'Level',
    dataIndex: 'level',
    key: 'level',
    width: 100,
    customRender: ({ text }: { text: string }) => {
      const colorMap: Record<string, string> = {
        error: 'red',
        warn: 'orange',
        warning: 'orange',
        info: 'blue',
        debug: 'default',
      };
      return h(Tag, { color: colorMap[String(text).toLowerCase()] ?? 'default' }, () =>
        String(text).toUpperCase(),
      );
    },
  },
  {
    title: 'Source',
    dataIndex: 'source',
    key: 'source',
    width: 150,
  },
  {
    title: 'Message',
    dataIndex: 'message',
    key: 'message',
    ellipsis: true,
  },
  {
    title: 'Details',
    dataIndex: 'details',
    key: 'details',
    ellipsis: true,
  },
];

const levelOptions = ['INFO', 'WARN', 'ERROR', 'DEBUG'];

// --------------- data fetching ---------------
async function fetchLogs() {
  loading.value = true;
  try {
    const params: Record<string, any> = {
      page: pagination.current,
      pageSize: pagination.pageSize,
    };
    if (filters.keyword) params.keyword = filters.keyword;
    if (filters.level) params.level = filters.level;

    const res = await getSystemLogsApi(params);
    // API may return array directly or paginated object
    dataSource.value = res.list ?? [];
    total.value = res.total ?? 0;
  } catch {
    // error handled by request interceptor
  } finally {
    loading.value = false;
  }
}

function handleSearch() {
  pagination.current = 1;
  fetchLogs();
}

function handleReset() {
  filters.keyword = '';
  filters.level = undefined;
  pagination.current = 1;
  fetchLogs();
}

function handleTableChange(pag: any) {
  pagination.current = pag.current;
  pagination.pageSize = pag.pageSize;
  fetchLogs();
}

// --------------- lifecycle ---------------
onMounted(() => {
  fetchLogs();
});
</script>

<template>
  <Page description="Browse system-level logs" title="System Logs">
    <Card>
      <!-- Filters -->
      <Form layout="inline" style="margin-bottom: 16px;">
        <FormItem label="Search">
          <InputSearch
            v-model:value="filters.keyword"
            placeholder="Search messages..."
            style="width: 260px;"
            @search="handleSearch"
          />
        </FormItem>
        <FormItem label="Level">
          <Select
            v-model:value="filters.level"
            placeholder="All"
            allow-clear
            style="width: 120px;"
            @change="handleSearch"
          >
            <SelectOption v-for="l in levelOptions" :key="l" :value="l">
              {{ l }}
            </SelectOption>
          </Select>
        </FormItem>
        <FormItem>
          <Space>
            <Button type="primary" @click="handleSearch">Search</Button>
            <Button @click="handleReset">Reset</Button>
          </Space>
        </FormItem>
      </Form>

      <!-- Table -->
      <Table
        :columns="columns"
        :data-source="dataSource"
        :loading="loading"
        :pagination="pagination"
        row-key="id"
        size="middle"
        @change="handleTableChange"
      />
    </Card>
  </Page>
</template>

// frontend-next/src/pages/caddy/system-log/index.tsx
import { PageContainer, ProTable } from '@ant-design/pro-components';
import { useIntl } from '@umijs/max';
import { Switch, Tag } from 'antd';
import React, { useRef, useState } from 'react';
import { fetchSystemLogs } from '@/services/system-log';
import type { ActionType, ProColumns } from '@ant-design/pro-components';

const getLevelColor = (level: string) => {
  const map: Record<string, string> = {
    info: 'blue',
    warn: 'orange',
    error: 'red',
    debug: 'default',
  };
  return map[level?.toLowerCase()] || 'default';
};

const CaddySystemLog: React.FC = () => {
  const intl = useIntl();
  const actionRef = useRef<ActionType>();
  const [autoRefresh, setAutoRefresh] = useState(false);

  const columns: ProColumns[] = [
    {
      title: intl.formatMessage({ id: 'system.log.time', defaultMessage: 'Time' }),
      dataIndex: 'timestamp',
      valueType: 'dateTime',
      width: 180,
      search: false,
    },
    {
      title: intl.formatMessage({ id: 'system.log.source', defaultMessage: 'Source' }),
      dataIndex: 'source',
      width: 120,
      valueType: 'select',
      valueEnum: {
        caddy: { text: 'Caddy' },
        system: { text: 'System' },
        app: { text: 'Application' },
      },
    },
    {
      title: intl.formatMessage({ id: 'system.log.level', defaultMessage: 'Level' }),
      dataIndex: 'level',
      width: 100,
      valueType: 'select',
      valueEnum: {
        info: { text: 'Info', status: 'Processing' },
        warn: { text: 'Warn', status: 'Warning' },
        error: { text: 'Error', status: 'Error' },
        debug: { text: 'Debug', status: 'Default' },
      },
      render: (_, record) => (
        <Tag color={getLevelColor(record.level)}>{record.level}</Tag>
      ),
    },
    {
      title: intl.formatMessage({ id: 'system.log.message', defaultMessage: 'Message' }),
      dataIndex: 'message',
      ellipsis: true,
      search: false,
    },
    {
      title: intl.formatMessage({ id: 'system.log.keyword', defaultMessage: 'Keyword' }),
      dataIndex: 'keyword',
      hideInTable: true,
    },
    {
      title: intl.formatMessage({ id: 'system.log.time.range', defaultMessage: 'Time Range' }),
      dataIndex: 'timeRange',
      valueType: 'dateTimeRange',
      hideInTable: true,
      search: {
        transform: (value: any) => ({
          startTime: value[0],
          endTime: value[1],
        }),
      },
    },
  ];

  return (
    <PageContainer>
      <div style={{ marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
        <span>{intl.formatMessage({ id: 'system.log.auto.refresh', defaultMessage: 'Auto Refresh' })}:</span>
        <Switch checked={autoRefresh} onChange={setAutoRefresh} />
      </div>
      <ProTable
        actionRef={actionRef}
        rowKey="id"
        columns={columns}
        request={async (params) => {
          try {
            const res = await fetchSystemLogs({ page: params.current || 1, pageSize: params.pageSize || 20, ...params });
            return {
              data: res?.data?.list || [],
              success: true,
              total: res?.data?.total || 0,
            };
          } catch (error) {
            return { data: [], success: false, total: 0 };
          }
        }}
        pagination={{
          defaultPageSize: 20,
          showSizeChanger: true,
          showQuickJumper: true,
        }}
        search={{
          labelWidth: 'auto',
          defaultCollapsed: false,
        }}
        expandable={{
          expandedRowRender: (record) => (
            <pre style={{ margin: 0, background: '#f5f5f5', padding: 16 }}>
              {JSON.stringify(record, null, 2)}
            </pre>
          ),
        }}
        polling={autoRefresh ? 5000 : undefined}
      />
    </PageContainer>
  );
};

export default CaddySystemLog;
