// frontend-next/src/pages/manage/menu/index.tsx
/**
 * Menu Management Page (Task 14.1)
 *
 * Tree-structured menu table with add/edit/delete operations.
 * Fields: name, path, component, i18nKey, icon, roles, order, hideInMenu.
 */
import { useEffect, useState, useCallback } from 'react';
import {
  Table,
  Button,
  Modal,
  Space,
  message,
  Card,
  Tag,
  Form,
  Input,
  InputNumber,
  Select,
  Switch,
  Popconfirm,
} from 'antd';
import { PageContainer } from '@ant-design/pro-components';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import { request } from '@/utils/request';

// ---------------------------------------------------------------------------
// Inline service functions for menu management
// ---------------------------------------------------------------------------

interface MenuItem {
  id: number;
  name: string;
  path: string;
  component?: string;
  i18nKey?: string;
  icon?: string;
  roles?: string[];
  order?: number;
  hideInMenu?: boolean;
  parentId?: number;
  children?: MenuItem[];
  createdAt: string;
  updatedAt: string;
}

async function fetchMenuTree() {
  return request<{ list: MenuItem[] }>({ url: '/api/menu/tree' });
}

async function fetchCreateMenu(data: Omit<MenuItem, 'id' | 'createdAt' | 'updatedAt'>) {
  return request<void>({ url: '/api/menu', method: 'post', data });
}

async function fetchUpdateMenu(id: number, data: Partial<MenuItem>) {
  return request<void>({ url: `/api/menu/${id}`, method: 'put', data });
}

async function fetchDeleteMenu(id: number) {
  return request<void>({ url: `/api/menu/${id}`, method: 'delete' });
}

async function fetchRoleOptions() {
  return request<{ list: { name: string; displayName: string }[] }>({ url: '/api/role/list' });
}

// ---------------------------------------------------------------------------
// Helper: flatten tree to find parent options
// ---------------------------------------------------------------------------

function flattenMenuTree(tree: MenuItem[], depth = 0): { value: number; label: string; depth: number }[] {
  const result: { value: number; label: string; depth: number }[] = [];
  for (const item of tree) {
    result.push({ value: item.id, label: `${'  '.repeat(depth)}${item.name}`, depth });
    if (item.children && item.children.length > 0) {
      result.push(...flattenMenuTree(item.children, depth + 1));
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Page component
// ---------------------------------------------------------------------------

export default function MenuManagementPage() {
  const [loading, setLoading] = useState(false);
  const [menuTree, setMenuTree] = useState<MenuItem[]>([]);
  const [roles, setRoles] = useState<{ name: string; displayName: string }[]>([]);

  // Modal state
  const [modalVisible, setModalVisible] = useState(false);
  const [editingMenu, setEditingMenu] = useState<MenuItem | null>(null);
  const [form] = Form.useForm();
  const [saving, setSaving] = useState(false);

  const loadMenuTree = useCallback(async () => {
    setLoading(true);
    const { data, error } = await fetchMenuTree();
    if (error) {
      message.error(error.message || 'Failed to load menu tree');
    } else if (data) {
      setMenuTree(data.list || []);
    }
    setLoading(false);
  }, []);

  const loadRoles = useCallback(async () => {
    const { data } = await fetchRoleOptions();
    if (data) {
      setRoles(data.list || []);
    }
  }, []);

  useEffect(() => {
    loadMenuTree();
    loadRoles();
  }, [loadMenuTree, loadRoles]);

  const handleAdd = (parentId?: number) => {
    setEditingMenu(null);
    form.resetFields();
    if (parentId) {
      form.setFieldsValue({ parentId });
    }
    setModalVisible(true);
  };

  const handleEdit = (menu: MenuItem) => {
    setEditingMenu(menu);
    form.setFieldsValue({
      name: menu.name,
      path: menu.path,
      component: menu.component,
      i18nKey: menu.i18nKey,
      icon: menu.icon,
      roles: menu.roles,
      order: menu.order,
      hideInMenu: menu.hideInMenu,
      parentId: menu.parentId,
    });
    setModalVisible(true);
  };

  const handleDelete = async (id: number) => {
    const { error } = await fetchDeleteMenu(id);
    if (error) {
      message.error(error.message || 'Failed to delete menu');
    } else {
      message.success('Menu deleted successfully');
      loadMenuTree();
    }
  };

  const handleSaveMenu = async () => {
    try {
      const values = await form.validateFields();
      setSaving(true);

      if (editingMenu) {
        const { error } = await fetchUpdateMenu(editingMenu.id, values);
        if (error) {
          message.error(error.message || 'Failed to update menu');
        } else {
          message.success('Menu updated successfully');
          setModalVisible(false);
          loadMenuTree();
        }
      } else {
        const { error } = await fetchCreateMenu(values);
        if (error) {
          message.error(error.message || 'Failed to create menu');
        } else {
          message.success('Menu created successfully');
          setModalVisible(false);
          loadMenuTree();
        }
      }
    } catch {
      // Form validation failed
    }
    setSaving(false);
  };

  const handleCancelModal = () => {
    setModalVisible(false);
    setEditingMenu(null);
    form.resetFields();
  };

  const parentOptions = flattenMenuTree(menuTree).map(opt => ({
    label: opt.label,
    value: opt.value,
  }));

  const columns: ColumnsType<MenuItem> = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      width: 180,
      render: (text: string) => <strong>{text}</strong>,
    },
    {
      title: 'Path',
      dataIndex: 'path',
      key: 'path',
      width: 200,
      render: (text: string) => <Tag color="blue">{text}</Tag>,
    },
    {
      title: 'Component',
      dataIndex: 'component',
      key: 'component',
      width: 180,
      ellipsis: true,
    },
    {
      title: 'Icon',
      dataIndex: 'icon',
      key: 'icon',
      width: 120,
    },
    {
      title: 'i18n Key',
      dataIndex: 'i18nKey',
      key: 'i18nKey',
      width: 150,
    },
    {
      title: 'Roles',
      dataIndex: 'roles',
      key: 'roles',
      width: 200,
      render: (menuRoles: string[]) => (
        <Space size={[0, 4]} wrap>
          {menuRoles?.map(r => (
            <Tag key={r} color="processing">
              {r}
            </Tag>
          ))}
        </Space>
      ),
    },
    {
      title: 'Order',
      dataIndex: 'order',
      key: 'order',
      width: 80,
      sorter: (a: MenuItem, b: MenuItem) => (a.order || 0) - (b.order || 0),
    },
    {
      title: 'Hide',
      dataIndex: 'hideInMenu',
      key: 'hideInMenu',
      width: 80,
      render: (hide: boolean) => (
        <Tag color={hide ? 'red' : 'green'}>{hide ? 'Yes' : 'No'}</Tag>
      ),
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 220,
      render: (_: unknown, record: MenuItem) => (
        <Space>
          <Button type="link" size="small" icon={<PlusOutlined />} onClick={() => handleAdd(record.id)}>
            Add Child
          </Button>
          <Button type="link" size="small" icon={<EditOutlined />} onClick={() => handleEdit(record)}>
            Edit
          </Button>
          <Popconfirm
            title="Are you sure you want to delete this menu item?"
            description="Child items will also be deleted."
            onConfirm={() => handleDelete(record.id)}
            okText="Yes"
            cancelText="No"
          >
            <Button type="link" danger size="small" icon={<DeleteOutlined />}>
              Delete
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <PageContainer title="Menu Management">
      <Card>
        {/* Toolbar */}
        <Space style={{ marginBottom: 16 }}>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => handleAdd()}>
            Add Root Menu
          </Button>
        </Space>

        {/* Tree table */}
        <Table<MenuItem>
          columns={columns}
          dataSource={menuTree}
          rowKey="id"
          loading={loading}
          pagination={false}
          scroll={{ x: 1400 }}
          expandable={{
            defaultExpandAllRows: true,
            childrenColumnName: 'children',
          }}
          size="middle"
        />
      </Card>

      {/* Add/Edit Menu Modal */}
      <Modal
        title={editingMenu ? 'Edit Menu' : 'Add Menu'}
        open={modalVisible}
        onOk={handleSaveMenu}
        onCancel={handleCancelModal}
        confirmLoading={saving}
        destroyOnClose
        width={600}
      >
        <Form form={form} layout="vertical" autoComplete="off">
          <Form.Item label="Parent Menu" name="parentId">
            <Select
              placeholder="Select parent menu (empty for root)"
              allowClear
              options={parentOptions}
            />
          </Form.Item>
          <Form.Item
            label="Name"
            name="name"
            rules={[{ required: true, message: 'Please enter menu name' }]}
          >
            <Input placeholder="Enter menu name" />
          </Form.Item>
          <Form.Item
            label="Path"
            name="path"
            rules={[{ required: true, message: 'Please enter route path' }]}
          >
            <Input placeholder="Enter route path (e.g. /manage/user)" />
          </Form.Item>
          <Form.Item label="Component" name="component">
            <Input placeholder="Enter component identifier (e.g. view.manage_user)" />
          </Form.Item>
          <Form.Item label="i18n Key" name="i18nKey">
            <Input placeholder="Enter i18n key (e.g. route.manage_user)" />
          </Form.Item>
          <Form.Item label="Icon" name="icon">
            <Input placeholder="Enter icon name (e.g. material-symbols:route)" />
          </Form.Item>
          <Form.Item label="Roles" name="roles">
            <Select
              mode="multiple"
              placeholder="Select allowed roles"
              options={roles.map(r => ({ label: r.displayName, value: r.name }))}
            />
          </Form.Item>
          <Form.Item label="Order" name="order" initialValue={0}>
            <InputNumber min={0} max={9999} style={{ width: '100%' }} placeholder="Sort order" />
          </Form.Item>
          <Form.Item label="Hide in Menu" name="hideInMenu" valuePropName="checked" initialValue={false}>
            <Switch checkedChildren="Yes" unCheckedChildren="No" />
          </Form.Item>
        </Form>
      </Modal>
    </PageContainer>
  );
}

// frontend-next/apps/web-antd/src/views/manage/menu/index.vue
<script lang="ts" setup>
import { computed, onMounted, reactive, ref } from 'vue';

import {
  Button,
  Card,
  Form,
  FormItem,
  Input,
  InputNumber,
  message,
  Modal,
  Popconfirm,
  Select,
  SelectOption,
  Space,
  Table,
  Tag,
} from 'ant-design-vue';

import { requestClient } from '#/api/request';

defineOptions({ name: 'ManageMenu' });

// --------------- types ---------------
interface MenuItem {
  id: number;
  title: string;
  path: string;
  icon: string;
  order: number;
  type: 'directory' | 'menu';
  status: string;
  parentId: number | null;
  children?: MenuItem[];
}

// --------------- placeholder API calls ---------------
async function getMenuListApi() {
  return requestClient.get<MenuItem[]>('/system/menu/list');
}

async function createMenuApi(data: Omit<MenuItem, 'children' | 'id'>) {
  return requestClient.post('/system/menu', data);
}

async function updateMenuApi(
  id: number,
  data: Partial<Omit<MenuItem, 'children' | 'id'>>,
) {
  return requestClient.put(`/system/menu/${id}`, data);
}

async function deleteMenuApi(id: number) {
  return requestClient.delete(`/system/menu/${id}`);
}

// --------------- state ---------------
const loading = ref(false);
const dataSource = ref<MenuItem[]>([]);
const flatList = ref<MenuItem[]>([]);
const modalVisible = ref(false);
const modalTitle = ref('Add Menu');
const editingId = ref<number | null>(null);
const submitting = ref(false);

const formState = reactive({
  icon: '',
  order: 0,
  parentId: null as number | null,
  path: '',
  title: '',
  type: 'menu' as 'directory' | 'menu',
});

// --------------- columns ---------------
const columns = [
  { dataIndex: 'title', key: 'title', title: 'Title', width: 200 },
  { dataIndex: 'path', key: 'path', title: 'Path', width: 200 },
  { dataIndex: 'icon', key: 'icon', title: 'Icon', width: 120 },
  { dataIndex: 'order', key: 'order', title: 'Order', width: 80 },
  { dataIndex: 'type', key: 'type', title: 'Type', width: 100 },
  { dataIndex: 'status', key: 'status', title: 'Status', width: 100 },
  { key: 'actions', title: 'Actions', width: 180 },
];

// --------------- helpers ---------------
/** Flatten nested tree to a flat list for parent select options */
function flattenTree(nodes: MenuItem[], result: MenuItem[] = []): MenuItem[] {
  for (const node of nodes) {
    result.push(node);
    if (node.children?.length) {
      flattenTree(node.children, result);
    }
  }
  return result;
}

/** Parent options excluding the item being edited */
const parentOptions = computed(() => {
  return flatList.value.filter(
    (item) => item.id !== editingId.value && item.type === 'directory',
  );
});

// --------------- data fetching ---------------
async function fetchData() {
  loading.value = true;
  try {
    dataSource.value = await getMenuListApi();
    flatList.value = flattenTree([...dataSource.value]);
  } catch {
    message.error('Failed to load menu list');
  } finally {
    loading.value = false;
  }
}

// --------------- modal actions ---------------
function openAddModal(parentId?: number) {
  modalTitle.value = 'Add Menu';
  editingId.value = null;
  formState.title = '';
  formState.path = '';
  formState.icon = '';
  formState.order = 0;
  formState.parentId = parentId ?? null;
  formState.type = 'menu';
  modalVisible.value = true;
}

function openEditModal(record: MenuItem) {
  modalTitle.value = 'Edit Menu';
  editingId.value = record.id;
  formState.title = record.title;
  formState.path = record.path;
  formState.icon = record.icon;
  formState.order = record.order;
  formState.parentId = record.parentId;
  formState.type = record.type;
  modalVisible.value = true;
}

async function handleSubmit() {
  if (!formState.title) {
    message.warning('Title is required');
    return;
  }
  if (!formState.path) {
    message.warning('Path is required');
    return;
  }

  submitting.value = true;
  try {
    if (editingId.value) {
      await updateMenuApi(editingId.value, { ...formState });
      message.success('Menu updated successfully');
    } else {
      await createMenuApi({ ...formState });
      message.success('Menu created successfully');
    }
    modalVisible.value = false;
    await fetchData();
  } catch {
    message.error('Operation failed');
  } finally {
    submitting.value = false;
  }
}

async function handleDelete(id: number) {
  try {
    await deleteMenuApi(id);
    message.success('Menu deleted successfully');
    await fetchData();
  } catch {
    message.error('Failed to delete menu');
  }
}
</script>

<template>
  <div class="p-5">
    <Card title="Menu Management">
      <template #extra>
        <Button type="primary" @click="openAddModal()">Add Menu</Button>
      </template>

      <Table
        :columns="columns"
        :data-source="dataSource"
        :loading="loading"
        :pagination="false"
        :default-expand-all-rows="true"
        row-key="id"
        size="middle"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'type'">
            <Tag :color="record.type === 'directory' ? 'orange' : 'blue'">
              {{ record.type }}
            </Tag>
          </template>
          <template v-if="column.key === 'status'">
            <Tag :color="record.status === 'active' ? 'green' : 'red'">
              {{ record.status }}
            </Tag>
          </template>
          <template v-if="column.key === 'actions'">
            <Space>
              <Button
                v-if="record.type === 'directory'"
                type="link"
                size="small"
                @click="openAddModal(record.id)"
              >
                Add Child
              </Button>
              <Button type="link" size="small" @click="openEditModal(record)">
                Edit
              </Button>
              <Popconfirm
                title="Are you sure to delete this menu? Child items will also be removed."
                ok-text="Yes"
                cancel-text="No"
                @confirm="handleDelete(record.id)"
              >
                <Button type="link" size="small" danger>Delete</Button>
              </Popconfirm>
            </Space>
          </template>
        </template>
      </Table>
    </Card>

    <Modal
      :open="modalVisible"
      :title="modalTitle"
      :confirm-loading="submitting"
      @cancel="modalVisible = false"
      @ok="handleSubmit"
    >
      <Form layout="vertical" style="margin-top: 16px;">
        <FormItem label="Title" required>
          <Input
            v-model:value="formState.title"
            placeholder="Enter menu title"
          />
        </FormItem>
        <FormItem label="Path" required>
          <Input
            v-model:value="formState.path"
            placeholder="e.g. /system/user"
          />
        </FormItem>
        <FormItem label="Icon">
          <Input
            v-model:value="formState.icon"
            placeholder="Icon name, e.g. UserOutlined"
          />
        </FormItem>
        <FormItem label="Parent">
          <Select
            v-model:value="formState.parentId"
            allow-clear
            placeholder="Select parent (none = root)"
          >
            <SelectOption :value="null">-- Root --</SelectOption>
            <SelectOption
              v-for="item in parentOptions"
              :key="item.id"
              :value="item.id"
            >
              {{ item.title }}
            </SelectOption>
          </Select>
        </FormItem>
        <FormItem label="Order">
          <InputNumber
            v-model:value="formState.order"
            :min="0"
            style="width: 100%;"
          />
        </FormItem>
        <FormItem label="Type">
          <Select v-model:value="formState.type">
            <SelectOption value="directory">Directory</SelectOption>
            <SelectOption value="menu">Menu</SelectOption>
          </Select>
        </FormItem>
      </Form>
    </Modal>
  </div>
</template>
