// frontend-next/src/pages/notification/log/index.tsx
import { PageContainer, ProTable } from '@ant-design/pro-components';
import { useIntl } from '@umijs/max';
import { Button, message, Modal, Tag } from 'antd';
import React, { useRef, useState } from 'react';
import { getLogList } from '@/services/notification';
import type { ActionType, ProColumns } from '@ant-design/pro-components';

const NotificationLog: React.FC = () => {
  const intl = useIntl();
  const actionRef = useRef<ActionType>();
  const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([]);

  const handleBatchDelete = () => {
    if (selectedRowKeys.length === 0) {
      message.warning(
        intl.formatMessage({
          id: 'notification.log.select.warning',
          defaultMessage: 'Please select at least one log',
        }),
      );
      return;
    }
    Modal.confirm({
      title: intl.formatMessage({
        id: 'notification.log.batch.delete.confirm',
        defaultMessage: 'Confirm Batch Delete',
      }),
      content: intl.formatMessage(
        {
          id: 'notification.log.batch.delete.content',
          defaultMessage: 'Are you sure you want to delete {count} logs?',
        },
        { count: selectedRowKeys.length },
      ),
      onOk: async () => {
        try {
          // Assume batch delete API exists
          message.success(
            intl.formatMessage({
              id: 'notification.log.batch.delete.success',
              defaultMessage: 'Logs deleted successfully',
            }),
          );
          setSelectedRowKeys([]);
          actionRef.current?.reload();
        } catch (error) {
          message.error(
            intl.formatMessage({
              id: 'notification.log.batch.delete.error',
              defaultMessage: 'Failed to delete logs',
            }),
          );
        }
      },
    });
  };

  const handleClearAll = () => {
    Modal.confirm({
      title: intl.formatMessage({
        id: 'notification.log.clear.all.confirm',
        defaultMessage: 'Confirm Clear All',
      }),
      content: intl.formatMessage({
        id: 'notification.log.clear.all.content',
        defaultMessage: 'Are you sure you want to clear all notification logs?',
      }),
      okType: 'danger',
      onOk: async () => {
        try {
          // Assume clear all API exists
          message.success(
            intl.formatMessage({
              id: 'notification.log.clear.all.success',
              defaultMessage: 'All logs cleared successfully',
            }),
          );
          setSelectedRowKeys([]);
          actionRef.current?.reload();
        } catch (error) {
          message.error(
            intl.formatMessage({
              id: 'notification.log.clear.all.error',
              defaultMessage: 'Failed to clear logs',
            }),
          );
        }
      },
    });
  };

  const getStatusTag = (status: string) => {
    const map: Record<string, { color: string; text: string }> = {
      success: { color: 'green', text: 'Success' },
      failed: { color: 'red', text: 'Failed' },
      pending: { color: 'default', text: 'Pending' },
    };
    const config = map[status] || { color: 'default', text: status };
    return <Tag color={config.color}>{config.text}</Tag>;
  };

  const columns: ProColumns[] = [
    {
      title: intl.formatMessage({ id: 'notification.log.time', defaultMessage: 'Time' }),
      dataIndex: 'timestamp',
      valueType: 'dateTime',
      width: 180,
      search: false,
    },
    {
      title: intl.formatMessage({ id: 'notification.log.channel', defaultMessage: 'Channel' }),
      dataIndex: 'channelName',
      width: 150,
      valueType: 'select',
    },
    {
      title: intl.formatMessage({ id: 'notification.log.rule', defaultMessage: 'Rule' }),
      dataIndex: 'ruleName',
      width: 200,
      search: false,
    },
    {
      title: intl.formatMessage({ id: 'notification.log.status', defaultMessage: 'Status' }),
      dataIndex: 'status',
      width: 100,
      valueType: 'select',
      valueEnum: {
        success: { text: 'Success', status: 'Success' },
        failed: { text: 'Failed', status: 'Error' },
        pending: { text: 'Pending', status: 'Default' },
      },
      render: (_, record) => getStatusTag(record.status),
    },
    {
      title: intl.formatMessage({ id: 'notification.log.job.status', defaultMessage: 'Job Status' }),
      dataIndex: 'jobStatus',
      width: 120,
      valueType: 'select',
      valueEnum: {
        completed: { text: 'Completed', status: 'Success' },
        running: { text: 'Running', status: 'Processing' },
        failed: { text: 'Failed', status: 'Error' },
      },
    },
    {
      title: intl.formatMessage({ id: 'notification.log.message', defaultMessage: 'Message' }),
      dataIndex: 'message',
      ellipsis: true,
      search: false,
    },
  ];

  return (
    <PageContainer>
      <ProTable
        actionRef={actionRef}
        rowKey="id"
        columns={columns}
        rowSelection={{
          selectedRowKeys,
          onChange: setSelectedRowKeys,
        }}
        toolBarRender={() => [
          <Button key="batch-delete" onClick={handleBatchDelete}>
            {intl.formatMessage({ id: 'notification.log.batch.delete', defaultMessage: 'Batch Delete' })}
          </Button>,
          <Button key="clear-all" danger onClick={handleClearAll}>
            {intl.formatMessage({ id: 'notification.log.clear.all', defaultMessage: 'Clear All' })}
          </Button>,
        ]}
        request={async (params) => {
          try {
            const res = await getLogList({ page: params.current || 1, pageSize: params.pageSize || 20, ...params });
            return {
              data: res?.data?.list || [],
              success: true,
              total: res?.data?.total || 0,
            };
          } catch (error) {
            return { data: [], success: false, total: 0 };
          }
        }}
        pagination={{
          defaultPageSize: 20,
          showSizeChanger: true,
          showQuickJumper: true,
        }}
        search={{
          labelWidth: 'auto',
        }}
      />
    </PageContainer>
  );
};

export default NotificationLog;

// frontend-next/apps/web-antd/src/views/notification/log/index.vue
<script lang="ts" setup>
import type { NotificationApi } from '#/api/notification';

import { onMounted, reactive, ref } from 'vue';

import {
  Button,
  Card,
  Popconfirm,
  Space,
  Table,
  Tag,
  message,
} from 'ant-design-vue';

import {
  batchDeleteNotificationLogsApi,
  clearNotificationLogsApi,
  deleteNotificationLogApi,
  getNotificationLogsApi,
} from '#/api/notification';

defineOptions({ name: 'NotificationLog' });

// ── List state ──────────────────────────────────────────────

const loading = ref(false);
const logs = ref<NotificationApi.NotificationLog[]>([]);
const selectedRowKeys = ref<string[]>([]);

const pagination = reactive({
  current: 1,
  pageSize: 20,
  total: 0,
});

async function fetchLogs() {
  loading.value = true;
  try {
    const data = await getNotificationLogsApi({
      current: pagination.current,
      pageSize: pagination.pageSize,
    });
    logs.value = Array.isArray(data) ? data : [];
    pagination.total = Array.isArray(data) ? data.length : 0;
  } finally {
    loading.value = false;
  }
}

// ── Table columns ───────────────────────────────────────────

const columns = [
  { dataIndex: 'channelName', key: 'channelName', title: 'Channel' },
  { dataIndex: 'ruleName', key: 'ruleName', title: 'Recipient' },
  { dataIndex: 'content', key: 'content', title: 'Subject', ellipsis: true },
  { dataIndex: 'status', key: 'status', title: 'Status' },
  { dataIndex: 'createdAt', key: 'createdAt', title: 'Sent At' },
  { key: 'actions', title: 'Actions', width: 100 },
];

// ── Row selection ───────────────────────────────────────────

const rowSelection = {
  onChange: (keys: string[]) => {
    selectedRowKeys.value = keys;
  },
  selectedRowKeys,
};

// ── Pagination change ───────────────────────────────────────

function handleTableChange(pag: any) {
  pagination.current = pag.current;
  pagination.pageSize = pag.pageSize;
  fetchLogs();
}

// ── Delete single log ───────────────────────────────────────

async function handleDelete(id: string) {
  try {
    await deleteNotificationLogApi(id);
    message.success('Log deleted');
    await fetchLogs();
  } catch {
    message.error('Delete failed');
  }
}

// ── Batch delete ────────────────────────────────────────────

async function handleBatchDelete() {
  if (selectedRowKeys.value.length === 0) {
    message.warning('Please select at least one log');
    return;
  }
  try {
    await batchDeleteNotificationLogsApi({ ids: selectedRowKeys.value });
    message.success(`${selectedRowKeys.value.length} logs deleted`);
    selectedRowKeys.value = [];
    await fetchLogs();
  } catch {
    message.error('Batch delete failed');
  }
}

// ── Clear all ───────────────────────────────────────────────

async function handleClearAll() {
  try {
    await clearNotificationLogsApi();
    message.success('All logs cleared');
    selectedRowKeys.value = [];
    await fetchLogs();
  } catch {
    message.error('Clear failed');
  }
}

// ── Init ────────────────────────────────────────────────────

onMounted(() => {
  fetchLogs();
});
</script>

<template>
  <div class="p-5">
    <Card title="Notification Logs">
      <template #extra>
        <Space>
          <Popconfirm
            title="Are you sure to delete the selected logs?"
            :disabled="selectedRowKeys.length === 0"
            @confirm="handleBatchDelete"
          >
            <Button danger :disabled="selectedRowKeys.length === 0">
              Batch Delete{{ selectedRowKeys.length > 0 ? ` (${selectedRowKeys.length})` : '' }}
            </Button>
          </Popconfirm>
          <Popconfirm
            title="Are you sure to clear all notification logs? This cannot be undone."
            @confirm="handleClearAll"
          >
            <Button danger>
              Clear All
            </Button>
          </Popconfirm>
        </Space>
      </template>

      <Table
        :columns="columns"
        :data-source="logs"
        :loading="loading"
        :pagination="{
          current: pagination.current,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (t: number) => `Total ${t} records`,
        }"
        :row-selection="rowSelection"
        row-key="id"
        size="middle"
        @change="handleTableChange"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'status'">
            <Tag
              :color="
                record.status === 'sent'
                  ? 'green'
                  : record.status === 'failed'
                    ? 'red'
                    : 'blue'
              "
            >
              {{ record.status }}
            </Tag>
          </template>

          <template v-if="column.key === 'createdAt'">
            {{ record.createdAt }}
          </template>

          <template v-if="column.key === 'content'">
            {{ record.content?.substring(0, 80) }}{{ record.content?.length > 80 ? '...' : '' }}
          </template>

          <template v-if="column.key === 'actions'">
            <Popconfirm
              title="Are you sure to delete this log?"
              @confirm="handleDelete(record.id)"
            >
              <Button size="small" type="link" danger>
                Delete
              </Button>
            </Popconfirm>
          </template>
        </template>
      </Table>
    </Card>
  </div>
</template>
